# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('stars', models.IntegerField()),
                ('ratings', models.IntegerField()),
                ('difficulty_points', models.IntegerField()),
                ('difficulty_ratings', models.IntegerField()),
            ],
        ),
    ]
