# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unblock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='difficulty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='difficulty_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
