# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unblock', '0002_auto_20170411_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
