# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unblock', '0004_puzzle_tiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='moves',
            field=models.SmallIntegerField(default=1),
        ),
    ]
