# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unblock', '0005_puzzle_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
